import test from 'node:test';
import assert from 'node:assert/strict';
import { decideAIIntent } from '../src/combat/ai.js';
import { createDemoBattleSession, demoAbilityDefinitions } from '../src/runtime/demoBattle.js';
import { startAbility } from '../src/combat/ability.js';
function fixture(){const s=createDemoBattleSession(),a=s.allies[0],e=s.enemies[0];a.x=0;a.y=0;e.x=.2;e.y=0;for(const c of ['heavy','special','awakening']){a.abilityState[c].phase='cooldown';a.abilityState[c].cooldownRemaining=8;}return {s,a,e,state:{}};}
const decide=f=>decideAIIntent({actor:f.a,enemies:[f.e],abilityDefinitions:demoAbilityDefinitions,nowMs:0,preparationState:f.state});
test('near-ready Special creates range before cooldown is ready',()=>{const f=fixture();f.a.abilityState.special.cooldownRemaining=1.5;const i=decide(f);assert.equal(i.movement,'retreat');assert.equal(i.category,'special');assert.equal(i.desiredRange,1.8);});
test('preparation commits skill and target, with range hysteresis instead of chattering',()=>{const f=fixture();f.a.abilityState.special.cooldownRemaining=1;decide(f);f.a.abilityState.awakening.cooldownRemaining=.5;assert.equal(decide(f).category,'special');f.e.x=1.8;assert.notEqual(decide(f).kind,'move');for(const x of [1.7,1.85,1.68,1.9]){f.e.x=x;assert.notEqual(decide(f).kind,'move');}f.e.x=2.2;assert.equal(decide(f).movement,'approach');});
test('ready prepared skill executes through shared ability API',()=>{const f=fixture();f.a.abilityState.special.cooldownRemaining=.5;decide(f);f.e.x=1.8;f.a.abilityState.special.phase='ready';const i=decide(f);assert.equal(i.kind,'ability');assert.equal(i.category,'special');assert.equal(startAbility({caster:f.a,slot:f.a.abilityState[i.category],definition:demoAbilityDefinitions[i.definitionId],target:f.e}),true);});
test('without preparation Basic still pursues; close Heavy does not cause a large retreat',()=>{const f=fixture();assert.equal(decide(f).category,'basic');f.a.abilityState.heavy.cooldownRemaining=1;const i=decide(f);assert.ok((i.desiredRange??.2)<=.45);});
test('manual override and KO invalidate preparation; release immediately returns AI',()=>{const f=fixture();f.a.abilityState.special.cooldownRemaining=1;decide(f);f.a.controlHandoff.registerPlayerInput(0);assert.equal(decide(f).reason,'player_override');assert.equal(f.state.category,null);f.a.controlHandoff.releasePlayerControl();assert.equal(decide(f).movement,'retreat');f.a.damage(f.a.maxHp);assert.equal(decide(f).reason,'ko');assert.equal(f.state.category,null);});
test('BattleSession integrates preparation movement before Special readiness',()=>{const f=fixture();for(const a of f.s.actors){for(const c of ['heavy','special','awakening']){a.abilityState[c].phase='cooldown';a.abilityState[c].cooldownRemaining=8;}}f.a.abilityState.special.cooldownRemaining=1;f.s.enemies[1].x=8;f.s.enemies[2].x=9;f.s.step(.05);assert.ok(f.a.x<0);});
test('new cooldown preparation never preempts a ready higher-priority active skill',()=>{const f=fixture();f.e.x=1.8;f.a.abilityState.heavy.cooldownRemaining=1;f.a.abilityState.awakening.phase='ready';f.a.abilityState.awakening.cooldownRemaining=0;const i=decide(f);assert.equal(i.kind,'ability');assert.equal(i.category,'awakening');assert.equal(f.state.category,null);});
test('preparation target stays committed during nearest-target drift and invalidates on target KO',()=>{const f=fixture();f.a.abilityState.special.cooldownRemaining=1;decide(f);const next=f.s.enemies[1];next.x=.1;next.y=0;let i=decideAIIntent({actor:f.a,enemies:[f.e,next],abilityDefinitions:demoAbilityDefinitions,nowMs:50,preparationState:f.state});assert.equal(i.targetId,f.e.instanceId);f.e.damage(f.e.maxHp);i=decideAIIntent({actor:f.a,enemies:[f.e,next],abilityDefinitions:demoAbilityDefinitions,nowMs:100,preparationState:f.state});assert.equal(i.targetId,next.instanceId);});
