import test from 'node:test';
import assert from 'node:assert/strict';
import {campaign,findStage} from '../src/campaign/data.js';
import {initialAcquisition,completeAcquisition} from '../src/acquisition/model.js';
import {stageRewardRows} from '../src/acquisition/presentation.js';
for(const chapter of campaign)test(`${chapter.chapterId}: all five stages expose first-clear and replay sets through generic transaction`,()=>{
 for(const stage of chapter.stages){const first=stage.reward.items.filter(i=>i.repeat==='firstClear'),replay=stage.reward.items.filter(i=>i.repeat==='repeatable');assert.ok(first.length>=2);assert.ok(replay.length>=1);assert.equal(stageRewardRows(stage,initialAcquisition()).length,first.length+replay.length);const a=completeAcquisition(initialAcquisition(),{stageId:stage.stageId,completionId:'first',outcome:'victory',reward:stage.reward}),b=completeAcquisition(a.state,{stageId:stage.stageId,completionId:'replay',outcome:'victory',reward:stage.reward});assert.deepEqual(a.grantedItems,first);assert.deepEqual(b.grantedItems,replay);assert.deepEqual(stageRewardRows(stage,b.state).map(r=>r.status),[...first.map(()=> 'CLAIMED'),...replay.map(()=> 'REPEATABLE')]);}
});
test('Chapter1 accepted reward content unchanged',()=>{assert.deepEqual(findStage('1-1').reward.items.map(i=>[i.characterId,i.quantity,i.repeat]),[['P4',3,'firstClear'],['P2',2,'firstClear'],['P2',1,'repeatable']]);assert.deepEqual(findStage('1-5').reward.items.map(i=>[i.characterId,i.quantity,i.repeat]),[['P5',3,'firstClear'],['P1',2,'firstClear'],['P5',2,'repeatable']]);});
test('future Chapter7 synthetic stage requires only reward data',()=>{const stage={stageId:'7-3',reward:{items:[{type:'characterShard',characterId:'P1',quantity:3,repeat:'firstClear'},{type:'characterShard',characterId:'P5',quantity:2,repeat:'firstClear'},{type:'characterShard',characterId:'P5',quantity:1,repeat:'repeatable'}]}};const a=completeAcquisition(initialAcquisition(),{...stage,completionId:'seven-first',outcome:'victory'}),b=completeAcquisition(a.state,{...stage,completionId:'seven-replay',outcome:'victory'});assert.equal(a.grantedItems.length,2);assert.deepEqual(b.grantedItems,[stage.reward.items[2]]);});
