import test from 'node:test';import assert from 'node:assert/strict';
import { createStageBattleSession } from '../src/campaign/battleFactory.js';import { findStage } from '../src/campaign/data.js';
import { decideAIIntent } from '../src/combat/ai.js';
const make=(team=['P1','P2','P3'])=>createStageBattleSession({...findStage('1-1'),selectedTeam:team,enemyLineup:['P1','P2','P3']},{rng:()=>.99});
function nearby(s){s.allies.forEach((a,i)=>{a.x=0;a.y=i*.1;});s.enemies.forEach((a,i)=>{a.x=1;a.y=i*.1;});}
function hold(s){s.actors.forEach(a=>s.holdPlayerControl(a.instanceId));}
function intent(s,id){const actor=s.actorById(id),c=s.teamContext(actor);return decideAIIntent({actor,enemies:c.enemies,allies:c.allies,abilityDefinitions:s.abilityDefinitions,nowMs:s.elapsedSeconds*1000});}
test('鹿蜀 engage and diagonal reposition remain bounds-safe',()=>{const s=make();nearby(s);s.enemies[0].x=2.5;const a=s.allies[0],old={x:a.x,y:a.y};assert.ok(s.usePlayerAbility('a1','heavy'));assert.ok(a.x>old.x);const before=a.y;s.usePlayerAbility('a1','special');assert.notEqual(a.y,before);assert.ok(s.drainDamageEvents().length>=2);});
test('猼訑 mitigation and caster area Awakening resolve each valid target once',()=>{const s=make();nearby(s);s.usePlayerAbility('a2','special');assert.equal(s.statuses.damageMultiplier('a2',0),.75);s.usePlayerAbility('a2','awakening');assert.deepEqual(s.drainDamageEvents().map(e=>e.targetId),['e1','e2','e3']);});
test('九尾狐 ranged/AoE targets once, air cast unchanged',()=>{const s=make(['P4','P2','P3']);nearby(s);s.enemies.forEach(e=>e.x=3);s.usePlayerAbility('a1','special');assert.equal(s.drainDamageEvents().length,3);s.allies[0].abilityState.heavy.phase='ready';s.enemies.forEach(e=>e.x=10);assert.ok(s.usePlayerAbility('a1','heavy'));assert.equal(s.drainDamageEvents().length,0);});
for(const [id,hits] of [['P1',3],['P5',4]])test(`${id} timed multi-hit total coefficient, KO cancels pending hits, Retry clean`,()=>{const s=make([id,'P2','P3']);nearby(s);hold(s);s.usePlayerAbility('a1','awakening');assert.equal(s.drainDamageEvents().length,1);for(let i=1;i<hits;i++){hold(s);s.step(.12);assert.equal(s.drainDamageEvents().length,1);}assert.equal(s.pendingHits.length,0);const t=make([id,'P2','P3']);nearby(t);hold(t);t.usePlayerAbility('a1','awakening');t.drainDamageEvents();t.allies[0].damage(10000);t.step(.5);assert.equal(t.drainDamageEvents().length,0);assert.equal(make([id,'P2','P3']).pendingHits.length,0);});
test('狌狌 chase uses ability movement and shared damage',()=>{const s=make(['P5','P2','P3']);nearby(s);s.enemies[0].x=2.5;s.usePlayerAbility('a1','special');assert.ok(s.allies[0].x>0);assert.equal(s.drainDamageEvents().length,1);});
test('赤鱬 healer threshold chooses lowest living ally; team threshold needs two',()=>{const s=make();nearby(s);assert.notEqual(intent(s,'a3').category,'special');s.allies[0].damage(150);assert.equal(intent(s,'a3').category,'special');assert.equal(intent(s,'a3').targetId,'a1');s.allies[1].damage(150);assert.equal(intent(s,'a3').category,'awakening');});
test('AI and player heal use exact same execution API; no manual HSA auto-use',()=>{const s=make();nearby(s);s.allies[0].damage(150);s.actors.filter(a=>a.instanceId!=='a3').forEach(a=>s.holdPlayerControl(a.instanceId));const chosen=intent(s,'a3');s.step(.05);assert.equal(s.drainHealEvents()[0].targetId,chosen.targetId);const m=make();nearby(m);m.allies[0].damage(150);hold(m);m.step(.05);assert.equal(m.drainHealEvents().length,0);assert.equal(m.allies[2].abilityState.special.phase,'ready');});
test('AoE AI prefers multiple enemies and ranged basic holds preferred distance',()=>{const s=make(['P4','P2','P3']);nearby(s);s.enemies.forEach(e=>e.x=3);s.allies[0].abilityState.awakening.phase='cooldown';s.allies[0].abilityState.awakening.cooldownRemaining=10;assert.equal(intent(s,'a1').category,'special');s.enemies[1].x=10;s.enemies[2].x=10;assert.notEqual(intent(s,'a1').category,'special');});
