import test from 'node:test';import assert from 'node:assert/strict';
import { createStageBattleSession } from '../src/campaign/battleFactory.js';import { findStage } from '../src/campaign/data.js';
import * as effects from '../src/combat/effectTargeting.js';
import { resolveDamage } from '../src/combat/combatResolver.js';
const session=()=>createStageBattleSession({...findStage('1-1'),selectedTeam:['P1','P2','P3'],enemyLineup:['P1','P2','P3']},{rng:()=>.99});
function hold(s){s.actors.forEach(a=>s.holdPlayerControl(a.instanceId));}
test('lowest HP percentage ally deterministic tie-break, ignores KO and duplicates',()=>{const s=session(),[a,b,c]=s.allies;a.damage(a.maxHp*.5);b.damage(b.maxHp*.5);c.damage(c.maxHp);assert.equal(effects.lowestHpAlly([b,c,a,b]).instanceId,'a1');});
test('single heal clamps, no crit/RNG, event is actual recovered HP',()=>{const s=session(),a=s.allies[0];a.damage(10);assert.equal(s.usePlayerAbility('a3','special'),true);assert.equal(a.hp,a.maxHp);assert.equal(s.drainHealEvents()[0].amount,10);assert.equal(s.drainDamageEvents().length,0);});
test('team heal each living ally once, never revives KO',()=>{const s=session();s.allies[0].damage(100);s.allies[1].damage(100);s.allies[2].damage(1);assert.ok(s.usePlayerAbility('a3','awakening'));const e=s.drainHealEvents();assert.equal(e.length,3);assert.equal(new Set(e.map(e=>e.targetId)).size,3);s.allies[0].damage(10000);s.allies[2].abilityState.awakening.phase='ready';s.usePlayerAbility('a3','awakening');assert.equal(s.allies[0].hp,0);assert.ok(s.drainHealEvents().every(e=>e.targetId!=='a1'));});
test('heal execution rejects an enemy and KO in ally contract',async()=>{const { canStartAbility }=await import('../src/combat/ability.js');const s=session(),actor=s.allies[2],slot=actor.abilityState.special,definition=s.abilityDefinitions[slot.definitionId];assert.equal(canStartAbility({caster:actor,slot,definition,target:s.enemies[0]}),false);s.allies[0].damage(10000);assert.equal(canStartAbility({caster:actor,slot,definition,target:s.allies[0]}),false);});
test('mitigation reduces damage, expires at simulation time, fresh session clean',()=>{const s=session(),a=s.allies[1],e=s.enemies[0];s.usePlayerAbility('a2','special');const opts={attacker:e,defender:a,attackerDefinition:s.characterDefinitions[e.definitionId],defenderDefinition:s.characterDefinitions[a.definitionId],abilityDefinition:s.abilityDefinitions[e.abilityState.basic.definitionId],rng:()=>.99};const base=resolveDamage(opts).amount;const protectedDamage=resolveDamage({...opts,damageMultiplier:s.statuses.damageMultiplier(a.instanceId,s.elapsedSeconds)}).amount;assert.equal(protectedDamage,base*.75);hold(s);s.step(3.99);assert.equal(s.statuses.damageMultiplier(a.instanceId,s.elapsedSeconds),.75);s.step(.01);assert.equal(s.statuses.damageMultiplier(a.instanceId,s.elapsedSeconds),1);assert.equal(session().statuses.damageMultiplier(a.instanceId,0),1);});
test('AoE deduplicates valid enemies with deterministic ordering',()=>{const s=session(),a=s.allies[0];s.enemies.forEach(e=>{e.x=a.x+1;e.y=a.y;});s.enemies[1].damage(10000);const targets=effects.areaTargets(a,[...s.enemies].reverse().concat(s.enemies),2.2,'enemy');assert.deepEqual(targets.map(t=>t.instanceId),['e1','e3']);});
test('self mitigation works with no enemy in range and does not damage',()=>{const s=session();assert.ok(s.usePlayerAbility('a2','special'));assert.equal(s.statuses.damageMultiplier('a2',0),.75);assert.equal(s.drainDamageEvents().length,0);});
