import test from 'node:test';
import assert from 'node:assert/strict';
import * as tier from '../src/acquisition/tier.js';
import {normalizeAcquisition,initialAcquisition,completeAcquisition} from '../src/acquisition/model.js';
import {createAcquisitionPersistence,ACQUISITION_SAVE_KEY} from '../src/acquisition/persistence.js';
const legacy=(counts={})=>({version:1,shardsByCharacterId:counts,claimedStageIds:['2-1'],completedBattleIds:['reward-id']});
const upgrade=(s,id='P1',expectedTier='T1',requestId='upgrade-1')=>tier.upgradeTier(s,{characterId:id,expectedTier,requestId});
test('pre-M4B baseline and shard recruits migrate earned/spent once and retain receipts',()=>{const s=normalizeAcquisition(legacy({P1:10,P4:15,P5:5}));assert.equal(s.version,2);assert.equal(s.shardsByCharacterId.P4,15);assert.deepEqual(s.spentShardsByCharacterId,{P1:0,P2:0,P3:0,P4:5,P5:5});assert.equal(s.tierByCharacterId.P4,'T1');assert.deepEqual(normalizeAcquisition(s),s);assert.deepEqual(s.completedBattleIds,['reward-id']);assert.deepEqual(s.claimedStageIds,['2-1']);});
test('locked4/5 then recruitment consumes exactly5 while lifetime earned remains5',()=>{let s=normalizeAcquisition(legacy({P4:4}));assert.equal(tier.characterProgress(s,'P4').tier,null);assert.equal(tier.characterProgress(s,'P4').progressLabel,'4 / 5');s=completeAcquisition(s,{stageId:'7-1',completionId:'new-win',outcome:'victory',reward:{items:[{type:'characterShard',characterId:'P4',quantity:1,repeat:'repeatable'}]}}).state;const p=tier.characterProgress(s,'P4');assert.equal(p.tier,'T1');assert.equal(p.earned,5);assert.equal(p.spent,5);assert.equal(p.available,0);assert.equal(p.canUpgrade,false);assert.deepEqual(normalizeAcquisition(s),s);});
for(const [earned,enabled] of [[4,false],[5,true],[10,true]])test(`T1 ${earned}/5 eligibility`,()=>{const p=tier.characterProgress(normalizeAcquisition(legacy({P1:earned})),'P1');assert.equal(p.progressLabel,`${earned} / 5`);assert.equal(p.canUpgrade,enabled);});
test('T1 10/5 -> T2 5/10, excess retained; duplicate/stale action never skips Tier',()=>{const s=normalizeAcquisition(legacy({P1:30})),before=structuredClone(s);const a=upgrade(s);assert.equal(a.upgraded,true);assert.equal(a.state.shardsByCharacterId.P1,30);assert.equal(a.state.spentShardsByCharacterId.P1,5);assert.equal(tier.characterProgress(a.state,'P1').progressLabel,'25 / 10');assert.deepEqual(upgrade(a.state).state,a.state);assert.deepEqual(upgrade(a.state,'P1','T1','fresh-stale').state,a.state);assert.deepEqual(s,before);const ten=upgrade(normalizeAcquisition(legacy({P1:10})));assert.equal(tier.characterProgress(ten.state,'P1').progressLabel,'5 / 10');});
for(const [earned,enabled] of [[14,false],[15,true]])test(`T2 ${earned-5}/10 eligibility`,()=>{const s=upgrade(normalizeAcquisition(legacy({P1:earned}))).state;assert.equal(tier.characterProgress(s,'P1').canUpgrade,enabled);});
test('T2->T3 costs10; MAX cannot upgrade and future rewards retain available surplus',()=>{let s=upgrade(normalizeAcquisition(legacy({P1:20}))).state;s=upgrade(s,'P1','T2','upgrade-2').state;const p=tier.characterProgress(s,'P1');assert.equal(p.tier,'T3');assert.equal(p.progressLabel,'MAX');assert.equal(p.spent,15);assert.equal(p.available,5);assert.equal(upgrade(s,'P1','T3','no-four').upgraded,false);s=completeAcquisition(s,{stageId:'7-1',completionId:'farm',outcome:'victory',reward:{items:[{type:'characterShard',characterId:'P1',quantity:2,repeat:'repeatable'}]}}).state;assert.equal(tier.characterProgress(s,'P1').available,7);assert.equal(tier.characterProgress(s,'P1').tier,'T3');});
test('locked/unknown/insufficient/empty request rejected with no spend',()=>{const s=initialAcquisition();for(const [id,t,r] of [['P4','T1','x'],['missing','T1','x'],['P1','T1','x'],['P1','T1','']])assert.equal(upgrade(s,id,t,r).upgraded,false);});
test('versioned migration and upgrade survive reload without touching Campaign/team/unrelated keys',()=>{const map=new Map([[ACQUISITION_SAVE_KEY,JSON.stringify(legacy({P1:10,P4:15}))],['campaign','keep'],['team','keep']]),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};const p=createAcquisitionPersistence(storage),s=p.load();assert.equal(JSON.parse(map.get(ACQUISITION_SAVE_KEY)).version,2);const a=upgrade(s,'P4');assert.equal(p.save(a.state),true);const reload=createAcquisitionPersistence(storage).load();assert.equal(tier.characterProgress(reload,'P4').progressLabel,'5 / 10');assert.deepEqual(createAcquisitionPersistence(storage).load(),reload);assert.equal(map.get('campaign'),'keep');assert.equal(map.get('team'),'keep');});
test('malformed ledger cannot become negative or invent free higher Tier; denied storage retains session upgrades',()=>{const s=normalizeAcquisition({version:2,shardsByCharacterId:{P1:10,P4:5},spentShardsByCharacterId:{P1:-5,P4:999,unknown:12},tierByCharacterId:{P1:'T3',P4:'T4',unknown:'T3'},completedUpgradeIds:['u',null,'u']});assert.equal(s.tierByCharacterId.P1,'T1');assert.equal(s.tierByCharacterId.P4,'T1');assert.equal(tier.characterProgress(s,'P4').available,0);assert.deepEqual(s.completedUpgradeIds,['u']);assert.equal(Object.hasOwn(s.tierByCharacterId,'unknown'),false);const p=createAcquisitionPersistence({getItem(){throw Error('denied');},setItem(){throw Error('denied');}}),a=upgrade(normalizeAcquisition(legacy({P1:10})));assert.equal(p.save(a.state),false);assert.deepEqual(p.load(),a.state);});
test('persisted structured Tier values sanitize without crashing or coercing arrays, earned and receipts preserved',()=>{
 for(const value of [{toString:null},['T2'],{},4,null]){const raw={version:2,shardsByCharacterId:{P1:20},tierByCharacterId:{P1:value},claimedStageIds:['2-1'],completedBattleIds:['win']},p=createAcquisitionPersistence({getItem:()=>JSON.stringify(raw),setItem(){}}),s=p.load();assert.equal(s.tierByCharacterId.P1,'T1');assert.equal(s.shardsByCharacterId.P1,20);assert.deepEqual(s.completedBattleIds,['win']);assert.deepEqual(s.claimedStageIds,['2-1']);}
});
